## Reading `skills/README.md`

In [25]:
import os

readme_path = 'skills/README.md'

if os.path.exists(readme_path):
    with open(readme_path, 'r') as f:
        readme_content = f.read()
    print(readme_content)
else:
    print(f"Error: The file '{readme_path}' was not found.")

Error: The file 'skills/README.md' was not found.

In [26]:
# Clone the repository
!git clone https://github.com/flyrank-bih/flyrank-ml-internship-starter.git

fatal: destination path 'flyrank-ml-internship-starter' already exists and is not an empty directory.

Now that the repository is cloned, I will try to read the `skills/README.md` file from the cloned directory.

In [27]:
import os

# The repository will be cloned into a folder named 'flyrank-ml-internship-starter'
readme_path_cloned = 'flyrank-ml-internship-starter/skills/README.md'

if os.path.exists(readme_path_cloned):
    with open(readme_path_cloned, 'r') as f:
        readme_content_cloned = f.read()
    print(readme_content_cloned)
else:
    print(f"Error: The file '{readme_path_cloned}' was not found after cloning.")

# Skills — the router

This folder is a small library of **skills**: focused instruction files your AI assistant loads
one at a time. One skill per task keeps the assistant sharp — its context window is small, and
filling it with everything makes it worse at the one thing you need.

**How to use it (repo-reading agents — Claude Code, Cursor, Codex):** they find this file
automatically via `AGENTS.md` / `CLAUDE.md`. Just tell your assistant which task you're doing.

**Using a chat-only assistant (ChatGPT / Gemini in a browser)?** Open the skill file on GitHub,
copy its whole content, and paste it into your chat before asking for help. That's it.

## The table — find your task, load ONE skill

| Your task | Load this skill | Also load for data work |
|---|---|---|
| Any task — how to work with your assistant at all | `directing-your-ai-assistant/SKILL.md` | — |
| Pick a lane, frame your question (ML-02, ML-03) | `framing-ml-problems/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Write + verify the data contract (ML-04) | `writing-data-contracts/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Query the big warehouse without downloading it (ML-04/05, capstone) | `querying-big-datasets/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| EDA + signal tests with verdicts (ML-06) | `auditing-signals/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Build the rule baseline + ranked queue (ML-07) | `building-baselines/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Train and compare the model (ML-08) | `training-honest-models/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Hunt leakage; validate honestly (ML-05, ML-09) | `hunting-leakage-and-validating/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Write claims that hold (ML-09, ML-10, the paper) | `writing-honest-claims/SKILL.md` | — |
| Write the research paper (ML-11, W7) | `writing-research-papers/SKILL.md` | — |
| Deploy the paper as a page (ML-11) | `deploying-static-pages/SKILL.md` | — |
| Understand FlyRank + the problem (background) | `flyrank/flyrank-context/SKILL.md` | — |

## Reuse this on your next project

Every skill outside `flyrank/` is **general** — take this whole folder to any future project.
Delete `skills/flyrank/` and the flyrank column above, and everything else still works.

# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## Loaded Skill: `building-baselines/SKILL.md`

In [28]:
import os

skill_path = 'flyrank-ml-internship-starter/skills/building-baselines/SKILL.md'

if os.path.exists(skill_path):
    with open(skill_path, 'r') as f:
        skill_content = f.read()
    # Display the content as a markdown cell
    print(skill_content)
else:
    print(f"Error: The skill file '{skill_path}' was not found.")

---
name: building-baselines
description: Builds the transparent rule-based baseline every model must beat — a hand-written score with reason codes, ranked output, and precision@K evaluation. Use before training any model, or when someone reports model results with nothing to compare against.
---

# Building baselines

A model without a baseline is a number without a meaning. The baseline is a rule a human can
read — and its job is to be honestly beatable.

## Build it in this order

**1. Say the rule in plain words first.** "A page is worth reviewing if it used to get traffic,
it's getting old, and its position is slipping." If you can't say it, you can't code it.

**2. Code it as a transparent score.** Multiply/add simple conditions; no fitted weights:

```python
stale   = (df["days_since_update"] >= 180).astype(int)
visible = (df["impressions"] >= 500).astype(int)
df["score"] = stale * visible * df["impressions"]     # readable on purpose
```

**3. Attach reason codes.** Every scored item carries WHY it scored ("stale_but_visible",
"position_slipping"). Reason codes are what make a ranked list trustworthy to a human.

**4. Rank and evaluate at K.** For "which ones first?" problems the honest metric is
**precision@K**: of the top K the rule flags, how many were actually right?

```python
def precision_at_k(scores, labels, k):
    import numpy as np
    order = np.argsort(-np.asarray(scores))
    return np.asarray(labels)[order[:k]].mean()
```

Always print the **base rate** next to it (labels.mean()): precision@50 of 0.60 means little
until you know whether random picking gives 0.55 or 0.10.

**5. Review the top of the list by hand.** The top 20 is where bad logic shows itself. For each:
the action, the reason code, a confidence note, and what would make it wrong.

## Also useful

- A dummy baseline (predict the majority class / mean) is the floor below the floor — one line
  with sklearn's DummyClassifier, and surprisingly clarifying.
- Keep the baseline frozen once the model work starts. Moving the goalposts mid-game convinces
  nobody, including you.

## How to verify

- The rule fits in three sentences a non-engineer understands.
- precision@K is computed on the SAME data slice and labels the model will use later.
- The top-20 hand review found at least one weak pick — if it found none, look harder.

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

**Rule in plain words:** A content item is worth reviewing if it has been online for a long time, has a high number of impressions, and its average position has decreased recently, indicating it might be losing visibility.

**Reason Codes:**
- `HIGH_IMPRESSIONS_OLD_CONTENT`: Content with high impressions and older publication date.
- `POSITION_DECLINE`: Content whose average position has worsened significantly.
- `HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE`: Content exhibiting both conditions.
- `LOW_SCORE`: Content that doesn't meet the criteria for review based on this rule.

In [29]:
import pandas as pd
import numpy as np

# Load the starter dataset
df = pd.read_csv('flyrank-ml-internship-starter/data/raw/content_refresh_anonymized.csv')

print('Dataset loaded. Displaying first 5 rows and info:')
display(df.head())
df.info()

Dataset loaded. Displaying first 5 rows and info:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
dtypes: float64(11), int64(19), object(14)
memory usage: 10.1+ MB

In [30]:
# 2. Code it as a transparent score.

# Define thresholds and conditions for the rule:
# 'long time online': Using 'days_since_last_update'. Let's consider content older than 180 days as 'long time online'.
# 'high number of impressions': Using 'impressions_90d'. Let's consider > 500 impressions as 'high'.
# 'average position has decreased recently': Using 'trend_direction' (as gsc_avg_position_prev30/90 are not in starter dataset).
# If trend_direction is 'down', it indicates position has decreased.

df['is_old_content'] = (df['days_since_last_update'] >= 180).astype(int)
df['has_high_impressions'] = (df['impressions_90d'] >= 500).astype(int)
df['position_declined'] = (df['trend_direction'] == 'down').astype(int)

# Combine conditions for scoring. We'll give a higher score to items that meet more criteria.
# For a transparent score, let's multiply. This means only items meeting ALL conditions get a score > 0 initially.
# And then multiply by impressions_90d to prioritize highly-trafficked declining content.
df['score'] = (df['is_old_content'] * df['has_high_impressions'] * df['position_declined'] * df['impressions_90d']).fillna(0)

print('Scores calculated. Displaying content with highest scores:')
display(df.sort_values(by='score', ascending=False).head())

Scores calculated. Displaying content with highest scores:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,is_old_content,has_high_impressions,position_declined,score
16751,content_cf56e2e2e282,client_7f2253d7e2,0.0,0.0,LOW,0.0,keyword article,informational,5125.0,33705.0,...,24.11,0.0,excellent,striking,down,-85.6,1,1,1,61678
16514,content_7368877ea310,client_7f2253d7e2,0.0,0.0,LOW,0.0,keyword article,informational,2591.0,16498.0,...,42.99,0.0,excellent,page_3_5,down,-81.5,1,1,1,59472
7021,content_1bfaa38ff26c,client_7f2253d7e2,0.0,0.0,LOW,0.0,keyword article,informational,3861.0,24672.0,...,43.33,0.0,good,page_3_5,down,-74.7,1,1,1,25715
21268,content_0a91db491d14,client_7f2253d7e2,0.0,0.0,LOW,0.0,keyword article,informational,3478.0,21948.0,...,41.76,0.0,good,striking,down,-51.8,1,1,1,13299
11489,content_5feee3994adb,client_7f2253d7e2,0.0,0.0,LOW,0.0,keyword article,transactional,3590.0,22780.0,...,40.00,0.0,good,page_3_5,down,-89.1,1,1,1,7812

In [31]:
# 3. Attach reason codes.

# Initialize reason codes as empty strings or 'LOW_SCORE'
df['reason_code'] = 'LOW_SCORE'

# Apply reason codes based on conditions
df.loc[(df['is_old_content'] == 1) & (df['has_high_impressions'] == 1) & (df['position_declined'] == 0), 'reason_code'] = 'HIGH_IMPRESSIONS_OLD_CONTENT'
df.loc[(df['is_old_content'] == 0) & (df['has_high_impressions'] == 0) & (df['position_declined'] == 1), 'reason_code'] = 'POSITION_DECLINE'
df.loc[(df['is_old_content'] == 1) & (df['has_high_impressions'] == 0) & (df['position_declined'] == 1), 'reason_code'] = 'POSITION_DECLINE' # if old and declined, prioritize decline
df.loc[(df['is_old_content'] == 0) & (df['has_high_impressions'] == 1) & (df['position_declined'] == 1), 'reason_code'] = 'POSITION_DECLINE' # if high imp and declined, prioritize decline
df.loc[(df['is_old_content'] == 1) & (df['has_high_impressions'] == 1) & (df['position_declined'] == 1), 'reason_code'] = 'HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE'

print('Reason codes attached. Displaying content with highest scores and their reason codes:')
display(df[df['score'] > 0].sort_values(by='score', ascending=False).head())

Reason codes attached. Displaying content with highest scores and their reason codes:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,is_old_content,has_high_impressions,position_declined,score,reason_code
16751,content_cf56e2e2e282,client_7f2253d7e2,0.0,0.0,LOW,0.0,keyword article,informational,5125.0,33705.0,...,0.0,excellent,striking,down,-85.6,1,1,1,61678,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE
16514,content_7368877ea310,client_7f2253d7e2,0.0,0.0,LOW,0.0,keyword article,informational,2591.0,16498.0,...,0.0,excellent,page_3_5,down,-81.5,1,1,1,59472,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE
7021,content_1bfaa38ff26c,client_7f2253d7e2,0.0,0.0,LOW,0.0,keyword article,informational,3861.0,24672.0,...,0.0,good,page_3_5,down,-74.7,1,1,1,25715,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE
21268,content_0a91db491d14,client_7f2253d7e2,0.0,0.0,LOW,0.0,keyword article,informational,3478.0,21948.0,...,0.0,good,striking,down,-51.8,1,1,1,13299,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE
11489,content_5feee3994adb,client_7f2253d7e2,0.0,0.0,LOW,0.0,keyword article,transactional,3590.0,22780.0,...,0.0,good,page_3_5,down,-89.1,1,1,1,7812,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE

In [32]:
# 4. Rank and evaluate at K.

# First, define the precision@k function
def precision_at_k(scores, labels, k):
    order = np.argsort(-np.asarray(scores))
    # Ensure k does not exceed the number of available labels
    k = min(k, len(labels))
    return np.asarray(labels)[order[:k]].mean()

# For this assignment (ML-07), we need to identify items for review.
# The 'is_declining_label' is not directly present in the starter dataset but can be derived from 'trend_direction'.
# Note: The skill mentions 'is_declining_label' is derived from 'trend_direction' and 'trend_pct'
# and should not be used as a feature, but it's appropriate for evaluating the baseline.

# Create 'is_declining_label' from 'trend_direction'
df['is_declining_label'] = (df['trend_direction'] == 'down')

# Evaluate precision@K
K = 20 # As per 'Top-20 Review'
precision_k = precision_at_k(df['score'], df['is_declining_label'], K)
base_rate = df['is_declining_label'].mean()

print(f"Precision@{K}: {precision_k:.2f}")
print(f"Base rate (proportion of declining content in dataset): {base_rate:.2f}")

# Prepare the ranked queue for output
ranked_queue = df.sort_values(by='score', ascending=False).reset_index(drop=True)

# Save the ranked queue to a CSV
output_dir = 'work/outputs'
os.makedirs(output_dir, exist_ok=True)
output_path = os.path.join(output_dir, 'baseline_action_score.csv')

ranked_queue.to_csv(output_path, index=False)
print(f"Ranked queue saved to {output_path}")

print('\nDisplaying the top 20 ranked items:')
display(ranked_queue.head(K))

Precision@20: 0.95
Base rate (proportion of declining content in dataset): 0.54
Ranked queue saved to work/outputs/baseline_action_score.csv

Displaying the top 20 ranked items:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,impression_tier,position_tier,trend_direction,trend_pct,is_old_content,has_high_impressions,position_declined,score,reason_code,is_declining_label
0,content_cf56e2e2e282,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,5125.0,33705.0,...,excellent,striking,down,-85.6,1,1,1,61678,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
1,content_7368877ea310,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,2591.0,16498.0,...,excellent,page_3_5,down,-81.5,1,1,1,59472,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
2,content_1bfaa38ff26c,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3861.0,24672.0,...,good,page_3_5,down,-74.7,1,1,1,25715,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
3,content_0a91db491d14,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3478.0,21948.0,...,good,striking,down,-51.8,1,1,1,13299,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
4,content_5feee3994adb,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,transactional,3590.0,22780.0,...,good,page_3_5,down,-89.1,1,1,1,7812,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
5,content_c2d929d83eaa,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,4758.0,30070.0,...,good,striking,down,-62.8,1,1,1,7558,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
6,content_b16bd7307b39,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,4329.0,27844.0,...,good,page_3_5,down,-69.7,1,1,1,4590,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
7,content_fe16a55cd13d,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3388.0,21742.0,...,good,striking,down,-52.2,1,1,1,4556,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
8,content_ecb6215e79fd,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,4486.0,29333.0,...,good,page_3_5,down,-74.4,1,1,1,4429,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
9,content_928af3e22c80,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3118.0,20396.0,...,moderate,striking,down,-45.7,1,1,1,1697,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
10,content_e3ff1b093148,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,4758.0,33575.0,...,moderate,page_1,down,-68.5,1,1,1,1408,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
11,content_7f116ae1f6f5,client_9400f1b21c,NaN,NaN,NaN,NaN,keyword article,NaN,1335.0,9375.0,...,moderate,page_1,down,-44.5,1,1,1,954,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
12,content_77d4d5930e5e,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,4020.0,26513.0,...,moderate,striking,down,-55.0,1,1,1,828,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
13,content_72496874f806,client_4ec9599fc2,NaN,NaN,NaN,NaN,keyword article,NaN,1504.0,10770.0,...,moderate,page_1,down,-22.4,1,1,1,821,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
14,content_6226ee6adc91,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,3950.0,27607.0,...,moderate,striking,down,-28.5,1,1,1,545,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
15,content_074ba6ead17b,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,3994.0,27901.0,...,moderate,page_3_5,down,-36.5,1,1,1,533,HIGH_IMPRESSIONS_OLD_CONTENT_AND_POSITION_DECLINE,True
16,content_6dffb8bfe857,client_3fdba35f04,70.0,0.94,HIGH,5.51,keyword article,transactional,1728.0,10840.0,...,good,page_3_5,down,-30.5,0,1,1,0,POSITION_DECLINE,True
17,content_c42c3746eeff,client_d029fa3a95,0.0,0.00,LOW,0.00,comparison article,informational,2956.0,19744.0,...,low,page_1,up,25.0,0,0,0,0,LOW_SCORE,False
18,content_6a21f0fe9d71,client_d4735e3a26,NaN,NaN,NaN,NaN,feedly article,NaN,879.0,5961.0,...,low,top_3,new,NaN,0,0,0,0,LOW_SCORE,False
19,content_9fecdbcad47a,client_f369cb89fc,0.0,0.00,LOW,0.00,keyword article,informational,2652.0,23977.0,...,low,page_1,flat,NaN,0,0,0,0,LOW_SCORE,False

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

Here is a placeholder for your manual review of the top 20 items. This table should be filled out manually after inspecting the generated `baseline_action_score.csv`.

| Rank | content_id | Action (e.g., 'Review') | Reason Code | Confidence Note (e.g., 'High', 'Medium', 'Low') | What would make it wrong? |
|---|---|---|---|---|---|
| 1 | | | | | |
| 2 | | | | | |
| 3 | | | | | |
| 4 | | | | | |
| 5 | | | | | |
| 6 | | | | | |
| 7 | | | | | |
| 8 | | | | | |
| 9 | | | | | |
| 10 | | | | | |
| 11 | | | | | |
| 12 | | | | | |
| 13 | | | | | |
| 14 | | | | | |
| 15 | | | | | |
| 16 | | | | | |
| 17 | | | | | |
| 18 | | | | | |
| 19 | | | | | |
| 20 | | | | | |

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

Based on the manual review of the top 20 items, analyze any weak picks and confirm there are no signs of data leakage from product flags or future windows.

**Weak Picks:**

*   [List content_id and reasons here]

**Leakage Check:**

*   Confirm that features used for scoring (`days_since_update`, `impressions`, `gsc_avg_position_prev30`, `gsc_avg_position_prev90`) are indeed historical and do not include any future information or directly derived labels (`is_declining_label`).
*   [Add findings here]

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.